spring:
  application:
    name: notification
  datasource:
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka